# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#    google.preauth_subscriber:
#        class: Pcg\GoogleBundle\Listener\ConnectPreAuthListener
#        arguments: ["@twig"]
#        tags:
#            - { name: kernel.event_subscriber }

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        #public: false

    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/App/{Console,Handler,Form,EventSubscriber,Twig,Security,Service}'

    App\Controller\:
        resource: '../../src/App/Controller'
        public: true
        tags: ['controller.service_arguments']

    # Autowiring commands
    CftfBundle\Command\:
        resource: '../../src/CftfBundle/Command'
        tags: ['console.command']

    Salt\UserBundle\Command\:
        resource: '../../src/Salt/UserBundle/Command'
        tags: ['console.command']

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%', db_table: 'auth_session', db_id_col: 'id', db_connection_options: "%pdo_options%" }

    salt.cache.external_docs:
        class: Symfony\Component\Cache\Adapter\PdoAdapter
        public: true
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'externalDoc-'
            - 0
